name: flow_new
channels:
  - defaults
dependencies:
  - aiohttp=3.7.4
  - aioredis=1.3.1
  - argcomplete=1.12.3
  - async-timeout=3.0.1
  - attrs=21.2.0
  - backcall=0.2.0
  - brotlipy=0.7.0
  - ca-certificates=2021.7.5
  - cachetools=4.2.2
  - certifi=2021.5.30
  - cffi=1.14.0
  - chardet=3.0.4
  - charset-normalizer=2.0.4
  - cryptography=3.4.7
  - debugpy=1.4.1
  - decorator=5.0.9
  - google-api-core=1.25.1
  - google-auth=1.33.0
  - googleapis-common-protos=1.53.0
  - hiredis=1.1.0
  - idna=3.2
  - importlib_metadata=3.10.0
  - ipykernel=6.2.0
  - ipython=7.26.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - matplotlib-inline=0.1.2
  - multidict=5.1.0
  - ncurses=6.2
  - opencensus=0.7.13
  - opencensus-context=0.1.2
  - openssl=1.1.1l
  - parso=0.8.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.2
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pygments=2.10.0
  - pyopenssl=20.0.1
  - pysocks=1.7.1
  - python=3.7.3
  - pytz=2021.1
  - pyzmq=22.2.1
  - readline=7.0
  - requests=2.26.0
  - setuptools=41.0.0
  - six=1.16.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.62.1
  - traitlets=5.0.5
  - typing-extensions=3.10.0.0
  - typing_extensions=3.10.0.0
  - wcwidth=0.2.5
  - wheel=0.37.0
  - xz=5.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zipp=3.5.0
  - zlib=1.2.11
  - pip:
    - absl-py==0.13.0
    - aiohttp-cors==0.7.0
    - alabaster==0.7.12
    - astor==0.8.1
    - awscli==1.16.309
    - babel==2.9.1
    - blessings==1.7
    - boto3==1.10.45
    - botocore==1.13.45
    - cached-property==1.5.2
    - click==8.0.1
    - cloudpickle==1.2.2
    - colorama==0.4.1
    - colorful==0.5.4
    - configparser==5.0.2
    - coverage==5.5
    - cycler==0.10.0
    - dill==0.3.4
    - dm-tree==0.1.6
    - docker-pycreds==0.4.0
    - docutils==0.15.2
    - filelock==3.0.12
    - funcsigs==1.0.2
    - future==0.18.2
    - gast==0.2.2
    - gitdb==4.0.7
    - gitpython==3.1.20
    - google-pasta==0.2.0
    - gpustat==0.6.0
    - grpcio==1.39.0
    - gym==0.14.0
    - h5py==3.3.0
    - imagesize==1.2.0
    - importlib-metadata==4.6.4
    - imutils==0.5.1
    - iniconfig==1.1.1
    - ipdb==0.13.9
    - jinja2==3.0.1
    - jmespath==0.10.0
    - joblib==0.10.3
    - jsonschema==3.2.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - lxml==4.4.1
    - lz4==3.1.3
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib==3.1.0
    - msgpack==1.0.2
    - nbformat==5.1.3
    - nose2==0.8.0
    - numpy==1.18.4
    - numpydoc==1.1.0
    - nvidia-ml-py3==7.352.0
    - opencv-python==4.5.3.56
    - opt-einsum==3.3.0
    - packaging==21.0
    - pandas==1.3.2
    - path==16.2.0
    - path-py==12.5.0
    - pathtools==0.1.2
    - plotly==2.4.0
    - pluggy==0.13.1
    - prometheus-client==0.11.0
    - promise==2.3
    - prompt-toolkit==3.0.20
    - protobuf==3.17.3
    - psutil==5.8.0
    - py==1.10.0
    - py-spy==0.3.9
    - pyglet==1.3.2
    - pyparsing==2.4.7
    - pyprind==2.11.2
    - pyrsistent==0.18.0
    - pytest==6.2.4
    - python-dateutil==2.7.3
    - pyyaml==5.2
    - ray==1.6.0
    - redis==3.5.3
    - rsa==3.4.2
    - s3transfer==0.2.1
    - scipy==1.1.0
    - sentry-sdk==1.3.1
    - setproctitle==1.2.2
    - shortuuid==1.0.1
    - smmap==4.0.0
    - snowballstemmer==2.1.0
    - sphinx==4.1.2
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - subprocess32==3.5.4
    - sumolib==1.9.2
    - tabulate==0.8.9
    - tensorboard==1.15.0
    - tensorboardx==2.4
    - tensorflow==1.15.2
    - tensorflow-estimator==1.15.1
    - termcolor==1.1.0
    - toml==0.10.2
    - torch==1.4.0
    - torch-tb-profiler==0.2.1
    - traci==1.9.2
    - urllib3==1.25.11
    - wandb==0.12.1
    - werkzeug==2.0.1
    - wrapt==1.12.1

